version: 2
steps:
  - name: Checkout code
    uses: actions/checkout@v3
    with:
      submodules: true # 서브모듈도 체크아웃
      fetch-depth: 0   # 전체 히스토리 가져오기

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
