name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main # 배포를 트리거하는 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true # 서브모듈 포함
        fetch-depth: 0

    # 2. Node.js 설정
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Hexo에 권장되는 Node.js 버전

    # 3. 의존성 설치
    - name: Install dependencies
      run: npm install

    # 4. Hexo 빌드
    - name: Build Hexo
      run: |
        npm install hexo-cli -g
        hexo clean
        hexo generate

    # 5. GitHub Pages로 배포
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
