name: Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      # 3. Install dependencies at the root
      - name: Install Root Dependencies
        run: npm install

      # 4. Install dependencies in themes/fexo (if package.json exists)
      - name: Install Theme Dependencies
        run: |
          if [ -f themes/fexo/package.json ]; then
            cd themes/fexo
            npm install
            cd ../../
          fi

      # 5. Verify Theme Directory
      - name: Verify Theme Directory
        run: ls themes/fexo

      # 6. Build Hexo
      - name: Build Hexo
        run: |
          npm install hexo-cli -g
          hexo clean
          hexo generate --debug

      # 7. Debug Generated Index.html
      - name: Debug Generated Index.html
        run: cat public/index.html

      # 8. Disable Jekyll
      - name: Disable Jekyll
        run: echo > public/.nojekyll

      # 9. Upload Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
