name: Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Repository Checkout
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      # 3. Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Ensure Local Theme is Used
      # This step ensures the `themes/fexo` directory is used from the repository.
      - name: Verify Local Theme
        run: ls ./themes/fexo

      # 5. Build Hexo
      - name: Build Hexo
        run: |
          npm install hexo-cli -g
          hexo clean
          hexo generate

      # 6. Disable Jekyll
      - name: Disable Jekyll
        run: echo > ./public/.nojekyll

      # 7. Upload Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
