name: Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository with submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      # 3. Install root dependencies
      - name: Install Root Dependencies
        run: npm install

      # 4. Install dependencies in themes/fexo (if package.json exists)
      - name: Install Theme Dependencies
        run: |
          if [ -f themes/fexo/package.json ]; then
            echo "Installing dependencies for themes/fexo"
            cd themes/fexo
            npm install
            cd ../../
          else
            echo "No package.json found in themes/fexo, skipping..."
          fi

      # 5. Verify Theme Directory
      - name: Verify Theme Directory
        run: |
          echo "Checking contents of themes/fexo"
          ls themes/fexo || echo "themes/fexo not found"

      # 6. Build Hexo
      - name: Build Hexo
        run: |
          npm install hexo-cli -g
          hexo clean
          hexo generate --debug

      # 7. Debug Generated Index.html
      - name: Debug Generated Index.html
        run: |
          if [ -f public/index.html ]; then
            echo "Generated public/index.html:"
            head -n 20 public/index.html
          else
            echo "Error: public/index.html not generated!"
            exit 1
          fi

      # 8. Disable Jekyll
      - name: Disable Jekyll
        run: echo > public/.nojekyll

      # 9. Upload Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      # 10. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 11. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
